Repository bedrock-viz/bedrock-viz, pull requests merged in 2020-07, with the labels that each got.

#50 Project restructure to separate header, src, test files
  CMakeLists.txt
  include/args.h
  include/asset.h
  include/config.h.in
  include/control.h
  include/define.h
  include/global.h
  include/logger.h
  include/minecraft/conversion.h
  include/minecraft/schematic.h
  include/minecraft/v2/base.h
  include/minecraft/v2/biome.h
  include/minecraft/v2/block.h
  include/minecraft/v2/enchantment.h
  include/minecraft/v2/entity.h
  include/minecraft/v2/item.h
  include/nbt.h
  include/util.h
  include/utils/fs.h
  include/utils/pointer_array.h
  include/utils/unknown_recorder.h
  include/world/check_spawn.h
  include/world/chunk_data.h
  include/world/common.h
  include/world/dimension_data.h
  include/world/misc.h
  include/world/point_conversion.h
  include/world/world.h
  include/xml/load_biome.h
  include/xml/load_block.h
  include/xml/load_enchantment.h
  include/xml/load_entity.h
  include/xml/load_item.h
  include/xml/loader.h
  src/minecraft/conversion.cc
  src/minecraft/schematic.cc
  src/minecraft/v2/base.cc
  src/minecraft/v2/biome.cc
  src/minecraft/v2/block.cc
  src/minecraft/v2/enchantment.cc
  src/minecraft/v2/entity.cc
  src/minecraft/v2/item.cc
  src/utils/fs.cc
  src/utils/unknown_recorder.cc
  src/world/check_spawn.cc
  src/world/chunk_data.cc
  src/world/common.cc
  src/world/dimension_data.cc
  src/world/misc.cc
  src/world/point_conversion.cc
  src/world/world.cc
  src/xml/load_biome.cc
  src/xml/load_block.cc
  src/xml/load_enchantment.cc
  src/xml/load_entity.cc
  src/xml/load_item.cc
  src/xml/loader.cc
  tests/example_test.cc
Labels: back-end

#48 remove placeholder if it's not going to be used
  src/world/world.cc
Labels: font-end

#60 Fix linking issues for libbedrock-viz
  CMakeLists.txt
Labels: bug

#61 Add issue templates for Bugs and Features
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
